### PR TITLE
1.0.10

### PR DESCRIPTION
**Pull request by IngmarVerheij**

### CODE REVIEW

**Comment by IngmarVerheij** [comment]
There were some inconsistencies in the previous build.
- When the same beacon came back, it wasn't detected.
- On first sight of a beacon an event is send immediately, throttle is skipped

**Review by peterdemartini — CHANGES_REQUESTED** [review]
`class Beacon extends EventEmiatter` should be `class Beacon extends EventEmitter`.

Why are we bypassing the throttle?

**Review by IngmarVerheij — COMMENTED** [review]
Removed the noThrottle

**Comment by IngmarVerheij** [comment]
You're right Peter, we shouldn't bypass it

**Pull request merged**
